apiVersion: v1
kind: Pod
metadata:
  name: spring-pod
  labels:
    app.kubernetes.io/name: proxy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - auth
  containers:
  - name: spring
    image: sangwoo0795/auth:1.3
    # image: sangwoo0795/auth:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
    # - name: password
      value: "password"
    ports:
    - containerPort: 8080
      name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: spring-svc
# spec:
#   type: NodePort
#   selector:
#     app.kubernetes.io/name: proxy
#   ports:
#   - name: name-of-service-port
#     protocol: TCP
#     port: 80
#     targetPort: http-web-svc