apiVersion: v1
kind: Pod
metadata:
  name: spring-friend-svc
  labels:
    app.kubernetes.io/name: proxy-friend
spec:
  containers:
  - name: spring
    image: sangwoo0795/friend:1.4
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 8081
      name: http-web-svc-f

---
apiVersion: v1
kind: Service
metadata:
  name: spring-friend-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy-friend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc-f