apiVersion: v1
kind: Pod
metadata:
  name: django-save
  labels:
    app.kubernetes.io/name: proxy-django-save
spec:
  containers:
  - name: django-save
    image: hyeonseong0917/matching_save:latest
    env:
    - name: PASSWORD
      value: "admin123"
    ports:
    - containerPort: 8000
      name: http-web-svc-d
    volumeMounts:
    - name: pv
      mountPath: /var
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: efs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: django-save-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy-django-save
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc-d