apiVersion: v1
kind: Pod
metadata:
  name: spring-notification
  labels:
    app.kubernetes.io/name: proxy-notification
spec:
  containers:
  - name: spring
    image: sangwoo0795/notification:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 8082
      name: http-web-svc-f

---
apiVersion: v1
kind: Service
metadata:
  name: spring-notification-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy-notification
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc-f