apiVersion: v1
kind: Pod
metadata:
  name: chat-pod
  labels:
    app.kubernetes.io/name: chat-pod
spec:
  containers:
  - name: chat-pod
    image: hyeonseong0917/chat:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 8090
      name: http-web-svc-f

---
apiVersion: v1
kind: Service
metadata:
  name: chat-pod-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: chat-pod
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc-f