# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: efs-pvc
# spec:
#   storageClassName: efs-sc
#   volumeName: efs-pv
#   accessModes:
#   - ReadWriteMany

#   resources:

#   requests:

#     storage: 5Gi

#   selector:

#     matchLabels:
#       app.kubernetes.io/name: proxy-django-test
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-provisioner"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi