apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: test-nginx
spec:
  type: NodePort
  selector:
    app: test-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http