apiVersion: v1
kind: Pod
metadata:
  name: django-post-test
  labels:
    app.kubernetes.io/name: proxy-django-test
spec:
  containers:
  - name: django-post-test
    image: hyeonseong0917/django-rest:latest
    env:
    - name: PASSWORD
      value: "admin123"
    ports:
    - containerPort: 8000
      name: http-web-svc-d
    volumeMounts:
    - name: pv
      mountPath: /var
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: efs-pvc
  
  

---
apiVersion: v1
kind: Service
metadata:
  name: django-post-svc-test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy-django-test
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc-d