apiVersion: v1
kind: Pod
metadata:
  name: spring-mysql
  labels:
    app: test
spec:
  containers:
  - name: spring-mysql
    image: sangwoo0795/auth:1.2
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    ports:
    - containerPort: 80