apiVersion: v1
kind: Pod
metadata:
  name: springboot
  labels:
    app: test
spec:
  containers:
  - name: test-spring
    image: sangwoo0795/auth0.0.2:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
      
      
    