apiVersion: v1
kind: Service
metadata:
  name: hello-spring
  labels:
    app: test
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http